FROM node:10-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json .
RUN npm install
RUN npm install -g nodemon

COPY . .
# Exports
EXPOSE 9999
CMD [ "npm", "run", "start.dev" ]